source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 4.2.10'
gem 'sprockets', '~> 3.7.2'

group :development, :test do
  gem 'vcr'
  gem 'webmock'
  gem 'cypress-on-rails', path: '../../'
end
