name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  rails_3_2:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.3
        bundler-cache: true 
    - name: Run tests
      run: bundle exec rake
    - run: gem uninstall -v '>= 2' -ax bundler || true
    - run: gem install bundler -v '< 2'
    - name: Run interaction tests
      run: ./specs_e2e/rails_3_2/test.sh
    - name: Save screenshots
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Rails 3 Screenshots
        path: specs_e2e/rails_3_2/cypress/screenshots

  rails_4_2:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake
    - run: gem uninstall -v '>= 2' -ax bundler || true
    - run: gem install bundler -v '< 2'
    - name: Run interaction tests
      run: ./specs_e2e/rails_4_2/test.sh
    - name: Save screenshots
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Rails 4 Screenshots
        path: specs_e2e/rails_4_2/spec/cypress/screenshots

  rails_5_2:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true 
    - name: Run tests
      run: bundle exec rake
    - name: Run interaction tests
      run: ./specs_e2e/rails_5_2/test.sh
    - name: Save screenshots
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Rails 5 Screenshots
        path: specs_e2e/rails_5_2/test/cypress/screenshots
